### ISSUE TITLE
Inactive hosts report

### ISSUE THREAD

**Issue by delmicio** [zoom/api-v1#12]
Hi, 
I can see there is a inactive hosts report on the account dashboard:
https://zoom.us/account/report/inactive

We currently get this information with the API REST calling all users, then removing those that are not hosts, then calling active meetings and finally removing those who are in active meetings.

if you have this endpoint `/report/inactive` internally it would be very helpful if you make it public.

This is mainly done because it's required to start a meeting with an inactive host.

**Comment by joshuawoodward** [comment]
@delmicio are you trying to start a meeting from a pool of virtual hosts or real users?

**Comment by delmicio** [comment]
@joshuawoodward we start meetings from virtual hosts. Do you have something in mind?

**Comment by joshuawoodward** [comment]
@delmicio You could use webhooks https://zoom.github.io/api/#webhooks to detect when a meeting has started/ended

When you receive the STARTED event you can flag the host as active/unavailable
When you receive the ENDED event you can flag the host as inactive/available

Not sure of your implementation, but if your datastore is MySQL, have a column for the host "in_use", or whatever, that's an INT and simply update that 1 or 0

To find an available host "SELECT * FROM `hosts` where `in_use` != 1"

Again depending on your implementation it may be safer to set "in_use" = 1 when you create the meeting, and just monitor for ENDED event to place the host back into the pool

**Comment by daviscraigs** [comment]
I have been looking for the REST API to call the inactive hosts report.  I am very interested in being able to determine which users are not using the service, and would like to see this for more than a 30 day window.  The report will provide something like, show account email, id, creation date where no meetings in the last 60/90 (user defined) days.

**Comment by cianphillips** [comment]
**# _Delete Inactive Users via API?_**


I am also looking for a way to use the https://zoom.us/account/report/inactive endpoint via API in order to cull old users automagically. We currently have people using Pro accounts who haven't had any activity in 3 years. Even the web interface neglects to provide a method to apply an action (such as delete) to the results of a report. I called support and their recommendation was to send support an email with the list of people we want deleted, then they would do the deleting for us. So handy! <grin>

Anyone find a creative way to use existing functional API calls to delete all users who have been inactive say, over 1.5 years?

**Comment by joshuawoodward** [comment]
@cianphillips 

Check out this gist https://gist.github.com/joshuawoodward/be56b3c455a05fd8475d25ebb68498d9

Finds users that haven't logged in within a certain threshold (hard coded at 90 days) then could allow you to downgrade them to free/basic users

Good approach over deleting them; you can have as many free users as you want, and if a user later needs to be upgraded to pro, easier than recreating the user. You could up the threshold to a comfortable spot (365+ days) and add a delete function https://zoom.github.io/api/#delete-user-permanently

**Comment by daviscraigs** [comment]
I ended up writing a PowerShell script that requires a few REST calls.
Run $Uri = "https://api.zoom.us/v1/user/list" to get a list of all users in ZoomFor each user run $Uri = "https://api.zoom.us/v1/report/getuserreport" to get their usage.You can specify start/end dates.Run $LicenseURI = "https://api.zoom.us/v1/user/update" and change the license to Basic if their usage report showed zero meetings.

Currently I run this manually, but plan to move this to a scheduled task after a few more test runs.  My fist pass recovered over 100 licenses, and only 3 or 4 users reached out and asked to have their account reset to PRO.
I added a section to read a text file email addresses that would never have their license changed from Pro to Basic, for those special users.

I also added a feature where the user receives an email advising that their license changed from Pro to Basic, so no one is surprised by this action.


~~~~~~~~~~~~~~~~
Craig Davis
davis_craig_s@yahoo.com
 

    On Thursday, November 2, 2017, 12:55:16 PM PDT, Joshua Woodward <notifications@github.com> wrote:  
 
 
@cianphillips

Check out this gist https://gist.github.com/joshuawoodward/be56b3c455a05fd8475d25ebb68498d9

Finds users that haven't logged in within a certain threshold (hard coded at 90 days) then could allow you to downgrade them to free/basic users

Good approach over deleting them; you can have as many free users as you want, and if a user later needs to be upgraded to pro, easier than recreating the user. You could up the threshold to a comfortable spot (365+ days) and add a delete function https://zoom.github.io/api/#delete-user-permanently

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by joshuawoodward** [comment]
This now available in v2 of the APIs https://zoom.github.io/api/#retrieve-hosts-report
